Remove Tox, use github workflow service container for webdriver
RedHatQE/widgetastic.core pull request #185
Opened 2020-09-24 01:01 UTC by mshriver

Probably a better option than trying to get tox-docker to work in #184 

Update readme for basic contribution guidelines
Define pytest.ini for default args

2020-09-24 05:26 UTC, quarckster approved these changes

2020-09-24 05:33 UTC, quarckster commented on .github/workflows/test_suite.yml
> +        options: "--shm-size=2g"
I believe tests failed because docker ran the container without `--network host`

2020-09-24 05:46 UTC, quarckster requested changes
Please see my comment.

2020-09-29 13:44 UTC, quarckster requested changes

2020-09-29 13:44 UTC, quarckster commented on testing/conftest.py
> +                "disable-dev-shm-usage",
Should it be `--disable-dev-shm-usage`?

2020-10-25 12:03 UTC, quarckster commented
@mshriver I've finally fixed all issues in this PR including docs.

2020-10-25 12:05 UTC, quarckster approved these changes

2020-10-26 12:12 UTC, merged

2020-10-26 12:13 UTC, mshriver commented
All credit to @quarckster here, thanks for resolving this!